version: "3.3"

services:
    app-database:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: Adm1npassword
            MYSQL_DATABASE: CalculationsDB
        ports:
            - 43306:3306
        volumes:
            - ./db/data:/var/lib/mysql

        flyway:
            image: flyway/flyway
            command: migrate
            volumes:
                - ./db:/flyway/sql
                - ./db:/flyway/conf
            depends_on: 
                - app-database

    frontend:
        image: christensenkim/devopscalc-web:${PROMOTE_BUILD_NUMBER}
        ports:
            - 24002:80

    application:
        image: christensenkim/devopscalc:${PROMOTE_BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Production
        ports: 
            - 24001:80