version: "3.3"

services:
  app-database:
    image: mysql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: Adm1npassword
        MYSQL_DATABASE: CalculationsDB
    volumes:
        - ./db/data:/var/lib/mysql

  frontend:
    depends_on: 
      - application

  application:
    depends_on: 
      - app-database

    flyway:
      image: flyway/flyway
      command: migrate
      volumes:
          - ./db:/flyway/sql
          - ./db:/flyway/conf
      depends_on: 
          - app-database