version: "3.3"

services:
    frontend:
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 23002:80

    application:
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 23001:80