version: "3.3"

services:
    app-database:
        ports:
            - 33306:3306
        volumes:
            - ./db/data:/var/lib/mysql
    frontend:
        image: christensenkim/devopscalc-web:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 25002:80

    application:
        image: christensenkim/devopscalc:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 25001:80