version: "3.3"

services:
  frontend:
    depends_on: 
      - application

  application:
    depends_on: 
      - app-database

    flyway:
      image: flyway/flyway
      command: migrate
      volumes:
          - ./db:/flyway/sql
          - ./db:/flyway/conf
      depends_on: 
          - app-database