version: "3.3"

services:
    app-database:
        ports:
          - 54306:3306
    frontend:
        image: christensenkim/devopscalc-web:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 25002:80

    application:
        image: christensenkim/devopscalc:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 25001:80