version: "3.3"

services:
    frontend:
        image: christensenkim/devopscalc-web:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 23002:80

    application:
        image: christensenkim/devopscalc:${BUILD_NUMBER}
        environment: 
            ASPNETCORE_ENVIRONMENT: Test
        ports: 
            - 23001:80