FROM node:latest as build

RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build --prod


FROM nginx:latest
COPY --from=build-step /app/dist/calculator-web /usr/share/nginx/html
