FROM nginx

WORKDIR /usr/share/nginx/html
COPY ./ /usr/share/nginx/html

RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=build /usr/local/app/dist/sample-angular-app /usr/share/nginx/html
EXPOSE 80