FROM node:latest as build

WORKDIR /usr/share/nginx/html
COPY ./ /usr/share/nginx/html

RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=build /usr/local/app/dist/Devops-Calculator /usr/share/nginx/html
EXPOSE 80